apiVersion: v1
kind: Service
metadata:
  name:  lab01-backend
spec:
  ports:
  - name:  lab01-backend
    port:  8080
    targetPort:  80
  selector:
    app:  lab01-backend
  type:  LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab01-backend
spec:
  selector:
    matchLabels:
      app: lab01-backend
  strategy:
    type: Recreate
  # Uncomment the following line to scale the deployment
  replicas: 6
  template:
    metadata:
      labels:
        app: lab01-backend
    spec:
      containers:
      - name: lab01-backend
        image: rodrigoevildead/dio-lab01-backend:latest
        ports:
        - containerPort: 80
