apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab01-backend
spec:
  selector:
    matchLabels:
      app: lab01-backend
  template:
    metadata:
      labels:
        app: lab01-backend
    spec:
      volumes:
        - name: lab01-pv-storage
          persistentVolumeClaim:
            claimName: lab01-pvc
      containers:
      - name: lab01-backend 
        image: rodrigosouza/dio-lab01-database:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: "/var/www/html"
            name: lab01-pv-storage
