apiVersion: v1
kind: Service
metadata:
  name:  lab01-frontend
spec:
  ports:
  - name:  lab01-frontend
    port:  80
    targetPort:  80
  selector:
    app:  lab01-frontend
  type:  LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lab01-frontend
spec:
  selector:
    matchLabels:
      app: lab01-frontend
  strategy:
    type: Recreate
  # Uncomment the following line to scale the deployment
  replicas: 2
  template:
    metadata:
      labels:
        app: lab01-frontend
    spec:
      containers:
      - name: lab01-frontend
        image: rodrigoevildead/dio-lab01-frontend:latest
        ports:
        - containerPort: 80
