apiVersion: v1
kind: PersistentVolume
metadata:
  name: lab01-pv
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lab01-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce  
  resources:
    requests:
      storage: 1Gi