apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp-deployment
  template:
    metadata:
      labels:
        app: myapp-deployment
    spec:
      automountServiceAccountToken: false
      containers:
      - name: myapp-php
        # labels:
        #   app: myapp-php
        image: denilsonbonatti/myapp-php:1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
          requests:
            memory: "64Mi"
            cpu: "250m"
            ephemeral-storage: "1Gi"
        ports:
          - containerPort: 80