apiVersion: v1
kind: Pod
metadata:
  name: myapp-php
  labels:
    name: myapp-php
spec:
  automountServiceAccountToken: false
  containers:
  - name: myapp-php
    image: denilsonbonatti/myapp-php:1.0
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
      requests:
        memory: "64Mi"
        cpu: "250m"
        ephemeral-storage: "1Gi"
    ports:
      - containerPort: 80
