apiVersion: v1
kind: Service
metadata:
  name: myapp-php-service
spec:
  type: LoadBalancer
  # type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
  selector:
    app: myapp-php